"""
multi_strategy_backtester.py — Walk-forward backtester for multiple parallel strategies.

Each strategy
  - Has its own HMM engine and StrategyOrchestrator trained on its symbol universe
  - Operates in an isolated sub-portfolio (its own cash + shares)
  - Receives capital from CapitalAllocator (rebalanced on a configurable interval)
  - Has every signal validated by PortfolioRiskManager before execution

Portfolio equity = sum of all strategy sub-portfolio equities.

CAPITAL MODEL
-------------
Portfolio has a shared reserve pool of cash.  Each strategy sub-portfolio starts
with initial_capital / n_strategies (before first allocator rebalance).

Allocator rebalance transfers cash between sub-portfolios by adjusting each
strategy's cash balance to match the target capital.  If a strategy is
over-weight, excess cash flows back to the reserve pool; if under-weight,
cash is pulled from the reserve.  This is a backtest simplification — live
trading would require liquidating positions to fund rebalancing.

SIGNAL SCALING FOR PRM
-----------------------
StrategyOrchestrator returns signals with position_size_pct relative to the
strategy's sub-portfolio.  Before PRM validation the signal is scaled to a
portfolio-relative fraction so PRM checks (aggregate exposure, symbol
concentration, leverage) operate on the same basis.

  portfolio_pct = signal.position_size_pct × leverage × (strat_equity / total_equity)

After PRM approves (possibly reduced), the approved portfolio_pct is unscaled
back to strategy-relative for execution against the sub-portfolio equity.

BENCHMARK COMPARISONS
---------------------
When run_benchmarks=True, three additional equity curves are generated:
  equal_weight  — same strategies, CapitalAllocator(equal_weight)
  best_single   — the single strategy with highest Calmar run alone
  buy_and_hold  — buy-and-hold of the most-traded symbol from bar 1

CLI
---
python main.py backtest --multi-strat --start 2020-01-01 --end 2024-12-31 --compare
"""

from __future__ import annotations

import copy
import logging
from dataclasses import dataclass, field
from itertools import combinations
from typing import Dict, List, Optional, Tuple

import numpy as np
import pandas as pd

from backtest.backtester import _ohlcv_from_close, _DEFAULT_HMM_CFG, _DEFAULT_STRAT_CFG
from core.capital_allocator import AllocationChange, CapitalAllocator
from core.hmm_engine import HMMEngine
from core.regime_strategies import BaseStrategy, Signal, StrategyOrchestrator
from core.risk_manager import PortfolioRiskManager, PortfolioState
from core.strategy_registry import StrategyRegistry
from data.feature_engineering import FeatureEngineer, hmm_feature_names as _hmm_feature_names
from data.feature_blending import blend_cross_symbol_features

logger = logging.getLogger(__name__)

_ANN = 252 ** 0.5          # annualisation factor for daily Sharpe/Sortino
_CORR_WARN_THRESHOLD = 0.80


# ── Proxy strategy used internally by the backtester ─────────────────────────

class _BacktestProxy(BaseStrategy):
    """
    Minimal concrete BaseStrategy used inside the multi-strategy backtester.

    The backtester manages signal generation externally via StrategyOrchestrator.
    This proxy exists solely to satisfy the StrategyRegistry's type check and
    provide the health-tracking interface (allocated_capital, record_daily_return).
    """

    def __init__(self, spec_name: str, total_alloc: float = 0.90) -> None:
        super().__init__()
        self._spec_name = spec_name
        self._total_alloc = total_alloc

    @property
    def name(self) -> str:
        return self._spec_name

    @property
    def total_allocation(self) -> float:
        return self._total_alloc

    def generate_signal(self, symbol, bars, regime_state):
        return None  # signals generated by StrategyOrchestrator, not here


# ── Data structures ────────────────────────────────────────────────────────────

@dataclass
class StrategySpec:
    """
    Configuration for one strategy in a multi-strategy run.

    Parameters
    ----------
    name            : Unique identifier used throughout results and logging.
    symbols         : Symbols this strategy trades.
    hmm_config      : HMM hyperparameter overrides (merged with defaults).
    strategy_config : StrategyOrchestrator config overrides.
    weight_min      : Minimum allocator weight for this strategy (fraction of total capital).
    weight_max      : Maximum allocator weight.
    hmm_symbol      : Symbol used to build HMM features.  Defaults to symbols[0].
    """

    name: str
    symbols: List[str]
    hmm_config: Optional[Dict] = None
    strategy_config: Optional[Dict] = None
    weight_min: float = 0.0
    weight_max: float = 1.0
    hmm_symbol: Optional[str] = None   # defaults to symbols[0] if None

    def primary_symbol(self) -> str:
        return self.hmm_symbol or self.symbols[0]


@dataclass
class StrategyAttribution:
    """Per-strategy performance metrics and portfolio contribution."""

    name: str
    symbols: List[str]

    # Standalone metrics
    total_return: float
    cagr: float
    sharpe: float
    sortino: float
    max_drawdown: float
    calmar: float

    # Portfolio-level contribution
    contribution_to_portfolio_return: float  # fraction of total portfolio return
    variance_fraction: float                 # share of portfolio variance

    # Time-series
    equity_curve: pd.Series
    returns: pd.Series
    weight_history: pd.Series              # allocator weight over time

    # Health events
    disabled_periods: List[Tuple[pd.Timestamp, pd.Timestamp]]  # [(start, end), ...]


@dataclass
class CorrelationReport:
    """Pairwise rolling correlation between strategy return series."""

    strategy_names: List[str]
    pairwise_avg: pd.DataFrame              # n × n, average 60-day rolling corr
    rolling_history: pd.DataFrame           # date index, column "A|B" for each pair
    pct_time_above_threshold: pd.DataFrame  # n × n, fraction of bars above threshold
    threshold: float = _CORR_WARN_THRESHOLD


@dataclass
class BenchmarkComparison:
    """Side-by-side comparison of the multi-strategy portfolio against baselines."""

    portfolio_calmar: float
    portfolio_sharpe: float

    equal_weight_calmar: float
    equal_weight_sharpe: float

    best_single_name: str
    best_single_calmar: float
    best_single_sharpe: float

    worst_single_name: str
    worst_single_calmar: float

    buy_and_hold_symbol: str
    buy_and_hold_total_return: float

    portfolio_beats_best_calmar: bool   # key question: is complexity worth it?


@dataclass
class MultiStrategyWindowResult:
    """Results for one walk-forward fold."""

    fold_id: int
    train_start: pd.Timestamp
    train_end: pd.Timestamp
    test_start: pd.Timestamp
    test_end: pd.Timestamp
    portfolio_equity: pd.Series           # total portfolio equity curve
    portfolio_returns: pd.Series          # daily returns
    strategy_equity: Dict[str, pd.Series]  # per-strategy equity
    strategy_returns: Dict[str, pd.Series] # per-strategy daily returns
    weight_history: Dict[str, pd.Series]   # allocator weight per bar
    allocator_changes: List[AllocationChange]
    trades: List[Dict]
    n_hmm_states: Dict[str, int]           # spec name → HMM n_states


@dataclass
class MultiStrategyBacktestResult:
    """Aggregated multi-strategy results across all walk-forward folds."""

    windows: List[MultiStrategyWindowResult]

    # Portfolio-level
    combined_portfolio_equity: pd.Series
    combined_portfolio_returns: pd.Series
    initial_capital: float
    final_equity: float
    total_return: float
    cagr: float
    sharpe: float
    sortino: float
    max_drawdown: float
    calmar: float
    allocator_turnover: float             # fraction of rebalances with |Δweight| > 5%

    # Per-strategy breakdown
    attributions: Dict[str, StrategyAttribution]

    # Cross-strategy correlation
    correlation_report: CorrelationReport

    # Structured outputs
    allocator_log: pd.DataFrame           # all AllocationChange records
    benchmark: Optional[BenchmarkComparison]

    metadata: Dict = field(default_factory=dict)


# ── Metrics helpers ────────────────────────────────────────────────────────────

def _metrics(returns: pd.Series, initial: float, final: float) -> Dict:
    """Compute standard performance metrics from a daily return series."""
    r = returns.dropna()
    if len(r) < 2:
        return dict(total_return=0.0, cagr=0.0, sharpe=0.0,
                    sortino=0.0, max_drawdown=0.0, calmar=0.0)

    n_bars = len(r)
    total_return = (final / max(initial, 1e-9)) - 1.0
    cagr = (1.0 + total_return) ** (252.0 / n_bars) - 1.0

    mean_r = float(r.mean())
    std_r  = float(r.std(ddof=1))
    sharpe = (mean_r / std_r * _ANN) if std_r > 0 else 0.0

    neg = r[r < 0]
    downside_std = float(neg.std(ddof=1)) if len(neg) > 1 else 0.0
    sortino = (mean_r / downside_std * _ANN) if downside_std > 0 else 0.0

    cum = (1.0 + r).cumprod()
    rolling_max = cum.cummax()
    dd_series = (cum - rolling_max) / rolling_max.clip(lower=1e-9)
    max_dd = float(abs(dd_series.min()))

    calmar = (cagr / max_dd) if max_dd > 0 else 0.0

    return dict(total_return=total_return, cagr=cagr, sharpe=sharpe,
                sortino=sortino, max_drawdown=max_dd, calmar=calmar)


def _build_correlation_report(
    strat_returns: Dict[str, pd.Series],
    window: int = 60,
    threshold: float = _CORR_WARN_THRESHOLD,
) -> CorrelationReport:
    """
    Compute pairwise rolling correlations between strategy return series.

    Returns a CorrelationReport with:
    - rolling_history: date × "A|B" column per pair, one row per bar
    - pairwise_avg: average rolling corr over the full period (n × n matrix)
    - pct_time_above_threshold: fraction of bars where rolling corr > threshold
    """
    names = list(strat_returns.keys())
    pairs = list(combinations(names, 2))

    rolling_cols: Dict[str, pd.Series] = {}
    for a, b in pairs:
        ra = strat_returns[a].dropna()
        rb = strat_returns[b].dropna()
        aligned = pd.concat([ra.rename("a"), rb.rename("b")], axis=1).dropna()
        if len(aligned) < window:
            col_key = f"{a}|{b}"
            rolling_cols[col_key] = pd.Series(dtype=float)
            continue
        rolling_corr = aligned["a"].rolling(window, min_periods=max(10, window // 4)).corr(aligned["b"])
        rolling_cols[f"{a}|{b}"] = rolling_corr

    rolling_history = pd.DataFrame(rolling_cols)

    # Build symmetric n × n matrices
    avg_mat = pd.DataFrame(np.eye(len(names)), index=names, columns=names)
    pct_mat = pd.DataFrame(np.zeros((len(names), len(names))), index=names, columns=names)
    for i in range(len(names)):
        pct_mat.iloc[i, i] = 1.0

    for a, b in pairs:
        col_key = f"{a}|{b}"
        series = rolling_cols.get(col_key, pd.Series(dtype=float)).dropna()
        if len(series) == 0:
            avg_val, pct_val = 0.0, 0.0
        else:
            avg_val = float(series.mean())
            pct_val = float((series > threshold).mean())

        avg_mat.loc[a, b] = avg_val
        avg_mat.loc[b, a] = avg_val
        pct_mat.loc[a, b] = pct_val
        pct_mat.loc[b, a] = pct_val

    return CorrelationReport(
        strategy_names=names,
        pairwise_avg=avg_mat,
        rolling_history=rolling_history,
        pct_time_above_threshold=pct_mat,
        threshold=threshold,
    )


# ── Main class ─────────────────────────────────────────────────────────────────

class MultiStrategyBacktester:
    """
    Walk-forward backtester for N strategies running in parallel.

    Parameters
    ----------
    initial_capital
        Total starting portfolio equity in USD.
    train_window
        Number of clean feature bars per IS fold (~252 = 1 year).
    test_window
        OOS bars per fold (~126 = 6 months).
    step_size
        Bars to advance IS window between folds.
    slippage_pct
        One-way slippage fraction per executed trade.
    risk_free_rate
        Annualised risk-free rate (not used in current Sharpe — Sharpe is excess
        return / vol against 0; set to 0.0 for pure return/vol ratio).
    allocator_approach
        One of: "equal_weight", "inverse_vol", "risk_parity",
        "performance_weighted".
    allocate_interval
        Bars between allocator rebalances.  Default 5 (weekly).
    reserve
        Fraction of capital held as cash reserve (not deployed to strategies).
    run_benchmarks
        Whether to compute BenchmarkComparison.
    zscore_window
        Rolling window for feature z-score standardisation (matches live default).
    """

    def __init__(
        self,
        initial_capital: float = 100_000.0,
        train_window: int = 252,
        test_window: int = 126,
        step_size: int = 126,
        slippage_pct: float = 0.0005,
        risk_free_rate: float = 0.045,
        allocator_approach: str = "inverse_vol",
        allocate_interval: int = 5,
        reserve: float = 0.10,
        run_benchmarks: bool = False,
        zscore_window: int = 252,
        sma_long: int = 200,
        sma_trend: int = 50,
        volume_norm_window: int = 50,
    ) -> None:
        self.initial_capital = initial_capital
        self.train_window = train_window
        self.test_window = test_window
        self.step_size = step_size
        self.slippage_pct = slippage_pct
        self.risk_free_rate = risk_free_rate
        self.allocator_approach = allocator_approach
        self.allocate_interval = allocate_interval
        self.reserve = reserve
        self.run_benchmarks = run_benchmarks
        self.zscore_window = zscore_window
        self.sma_long = sma_long
        self.sma_trend = sma_trend
        self.volume_norm_window = volume_norm_window
        self._result: Optional[MultiStrategyBacktestResult] = None

    # ── Public API ─────────────────────────────────────────────────────────────

    def run(
        self,
        prices: pd.DataFrame,
        specs: List[StrategySpec],
        portfolio_rm_config: Optional[Dict] = None,
        progress_callback=None,
    ) -> MultiStrategyBacktestResult:
        """
        Execute the full walk-forward multi-strategy backtest.

        Parameters
        ----------
        prices
            Wide-format close prices, shape (n_bars, n_symbols).
            Must contain all symbols referenced by every StrategySpec.
        specs
            List of StrategySpec — one entry per strategy.
        portfolio_rm_config
            Keyword overrides for PortfolioRiskManager constructor.
        progress_callback
            Callable(fold_id, n_folds, phase, info_dict) for progress reporting.
        """
        if len(specs) < 2:
            raise ValueError("MultiStrategyBacktester requires at least 2 strategies.")

        prm_kwargs = portfolio_rm_config or {}
        portfolio_rm = PortfolioRiskManager(**prm_kwargs)

        # ── Build per-spec OHLCV and features ─────────────────────────────────
        ohlcv_per_spec: Dict[str, Dict[str, pd.DataFrame]] = {}
        features_per_spec: Dict[str, pd.DataFrame] = {}
        clean_features_per_spec: Dict[str, pd.DataFrame] = {}

        for spec in specs:
            ohlcv: Dict[str, pd.DataFrame] = {}
            for sym in spec.symbols:
                if sym not in prices.columns:
                    raise ValueError(
                        f"Strategy '{spec.name}' symbol '{sym}' not found in prices."
                    )
                ohlcv[sym] = _ohlcv_from_close(prices[sym])
            ohlcv_per_spec[spec.name] = ohlcv

            primary_sym = spec.primary_symbol()
            hmm_cfg = {**_DEFAULT_HMM_CFG, **(spec.hmm_config or {})}

            fe = FeatureEngineer(
                zscore_window=self.zscore_window,
                sma_long=self.sma_long,
                sma_trend=self.sma_trend,
                volume_norm_window=self.volume_norm_window,
            )
            raw_features = fe.build_feature_matrix(
                ohlcv[primary_sym],
                feature_names=_hmm_feature_names(hmm_cfg),
                dropna=False,
            )
            raw_features = blend_cross_symbol_features(
                raw_features,
                {s: ohlcv[s] for s in spec.symbols},
                feature_engineer=fe,
                blend_exclude=hmm_cfg.get("blend_exclude", []),
                min_bars=0,
            )
            features_per_spec[spec.name] = raw_features
            clean_mask = raw_features.notna().all(axis=1)
            clean_features_per_spec[spec.name] = raw_features[clean_mask]

            logger.info(
                "Strategy '%s': %d total bars → %d clean feature bars",
                spec.name, len(raw_features), clean_mask.sum(),
            )

        # ── Align clean timestamps across all strategies ───────────────────────
        common_clean_idx = None
        for spec in specs:
            idx = clean_features_per_spec[spec.name].index
            common_clean_idx = idx if common_clean_idx is None else common_clean_idx.intersection(idx)

        if common_clean_idx is None or len(common_clean_idx) == 0:
            raise ValueError("No common clean feature timestamps across strategies.")

        aligned_features: Dict[str, pd.DataFrame] = {
            spec.name: clean_features_per_spec[spec.name].loc[common_clean_idx]
            for spec in specs
        }
        n_clean = len(common_clean_idx)

        logger.info(
            "Common clean bars across %d strategies: %d  [%s .. %s]",
            len(specs), n_clean,
            common_clean_idx[0].date(), common_clean_idx[-1].date(),
        )

        # ── Walk-forward windows ───────────────────────────────────────────────
        windows_idx = self._generate_windows(n_clean)
        if not windows_idx:
            raise ValueError(
                f"Insufficient common data for walk-forward backtest. "
                f"Need ≥ {self.train_window + self.test_window} aligned bars, got {n_clean}."
            )

        logger.info(
            "Multi-strategy walk-forward: %d folds | IS=%d | OOS=%d | step=%d",
            len(windows_idx), self.train_window, self.test_window, self.step_size,
        )

        # ── Strategy configs ───────────────────────────────────────────────────
        strategy_configs_for_alloc = {
            spec.name: {"weight_min": spec.weight_min, "weight_max": spec.weight_max}
            for spec in specs
        }

        # ── Run folds ─────────────────────────────────────────────────────────
        equity = self.initial_capital
        fold_results: List[MultiStrategyWindowResult] = []

        for fold_id, (is_s, is_e, oos_s, oos_e) in enumerate(windows_idx):
            is_features = {spec.name: aligned_features[spec.name].iloc[is_s:is_e] for spec in specs}
            oos_features = {spec.name: aligned_features[spec.name].iloc[oos_s:oos_e] for spec in specs}

            first_is = is_features[specs[0].name]
            if len(first_is) < _DEFAULT_HMM_CFG.get("min_train_bars", 120):
                logger.warning("Fold %d: insufficient IS bars — skipping.", fold_id)
                continue
            if len(oos_features[specs[0].name]) == 0:
                logger.warning("Fold %d: empty OOS — skipping.", fold_id)
                continue

            if progress_callback:
                progress_callback(fold_id, len(windows_idx), "training", {
                    "is_start": first_is.index[0].date(),
                    "is_end":   first_is.index[-1].date(),
                    "equity":   equity,
                })

            try:
                wr = self._run_multi_window(
                    fold_id=fold_id,
                    prices=prices,
                    ohlcv_per_spec=ohlcv_per_spec,
                    is_features=is_features,
                    oos_features=oos_features,
                    start_equity=equity,
                    specs=specs,
                    allocator=CapitalAllocator(
                        approach=self.allocator_approach,
                        strategy_configs=strategy_configs_for_alloc,
                        total_capital=equity,
                        reserve=self.reserve,
                        rebalance_threshold=0.05,
                    ),
                    portfolio_rm=portfolio_rm,
                )
            except Exception as exc:
                logger.error("Fold %d failed: %s — skipping.", fold_id, exc, exc_info=True)
                continue

            fold_results.append(wr)
            if len(wr.portfolio_equity) > 0:
                equity = float(wr.portfolio_equity.iloc[-1])

            if progress_callback:
                progress_callback(fold_id, len(windows_idx), "complete", {
                    "oos_start": wr.test_start.date(),
                    "oos_end":   wr.test_end.date(),
                    "equity":    equity,
                })

        if not fold_results:
            raise RuntimeError("All folds failed — no result produced.")

        # ── Stitch curves ──────────────────────────────────────────────────────
        combined_portfolio_equity = pd.concat(
            [w.portfolio_equity for w in fold_results]
        ).sort_index()
        combined_portfolio_returns = pd.concat(
            [w.portfolio_returns for w in fold_results]
        ).sort_index()

        combined_strat_equity: Dict[str, pd.Series] = {}
        combined_strat_returns: Dict[str, pd.Series] = {}
        combined_weight_history: Dict[str, pd.Series] = {}

        for spec in specs:
            eq = pd.concat(
                [w.strategy_equity.get(spec.name, pd.Series(dtype=float)) for w in fold_results]
            ).sort_index()
            ret = pd.concat(
                [w.strategy_returns.get(spec.name, pd.Series(dtype=float)) for w in fold_results]
            ).sort_index()
            wh = pd.concat(
                [w.weight_history.get(spec.name, pd.Series(dtype=float)) for w in fold_results]
            ).sort_index()
            combined_strat_equity[spec.name] = eq
            combined_strat_returns[spec.name] = ret
            combined_weight_history[spec.name] = wh

        all_alloc_changes = [c for w in fold_results for c in w.allocator_changes]

        # ── Portfolio-level metrics ────────────────────────────────────────────
        port_m = _metrics(
            combined_portfolio_returns,
            self.initial_capital,
            float(combined_portfolio_equity.iloc[-1]),
        )

        # ── Allocator turnover ─────────────────────────────────────────────────
        meaningful_changes = sum(
            1 for c in all_alloc_changes if abs(c.new_weight - c.old_weight) > 0.05
        )
        total_rebalance_events = max(len(all_alloc_changes), 1)
        allocator_turnover = meaningful_changes / total_rebalance_events

        # ── Per-strategy attribution ───────────────────────────────────────────
        attributions: Dict[str, StrategyAttribution] = {}
        total_port_return = port_m["total_return"]

        for spec in specs:
            eq = combined_strat_equity[spec.name]
            ret = combined_strat_returns[spec.name]
            wh = combined_weight_history[spec.name]

            strat_initial = self.initial_capital / len(specs)
            strat_final = float(eq.iloc[-1]) if len(eq) > 0 else strat_initial
            sm = _metrics(ret, strat_initial, strat_final)

            # Contribution to portfolio return: weighted average daily return
            aligned = pd.concat(
                [ret.rename("s"), wh.rename("w"), combined_portfolio_returns.rename("p")],
                axis=1,
            ).dropna()
            if len(aligned) > 0:
                contrib = float((aligned["w"] * aligned["s"]).sum())
                port_total_r = float((aligned["p"]).sum())
                contribution = (contrib / port_total_r) if abs(port_total_r) > 1e-12 else 0.0
            else:
                contribution = 0.0

            # Variance contribution
            if len(aligned) > 2:
                cov_matrix = aligned[["s"]].join(
                    pd.DataFrame({"w": aligned["w"]})
                ).dropna()
                # Simple: variance_fraction = var(strat) * avg_weight^2 / var(portfolio)
                var_p = float(combined_portfolio_returns.var())
                var_s = float(ret.var())
                avg_w = float(wh.mean()) if len(wh) > 0 else 0.0
                var_fraction = (var_s * avg_w ** 2) / var_p if var_p > 0 else 0.0
            else:
                var_fraction = 0.0

            # Disabled periods: consecutive blocks where is_enabled would be False
            # We detect them from returns where the strategy is flat (0) after
            # prior non-zero — approximated from the weight_history dropping to 0
            disabled_periods: List[Tuple] = []
            if len(wh) > 0:
                was_disabled = (wh == 0.0)
                block_start: Optional[pd.Timestamp] = None
                for ts, disabled in was_disabled.items():
                    if disabled and block_start is None:
                        block_start = ts
                    elif not disabled and block_start is not None:
                        disabled_periods.append((block_start, ts))
                        block_start = None
                if block_start is not None:
                    disabled_periods.append((block_start, wh.index[-1]))

            attributions[spec.name] = StrategyAttribution(
                name=spec.name,
                symbols=spec.symbols,
                total_return=sm["total_return"],
                cagr=sm["cagr"],
                sharpe=sm["sharpe"],
                sortino=sm["sortino"],
                max_drawdown=sm["max_drawdown"],
                calmar=sm["calmar"],
                contribution_to_portfolio_return=contribution,
                variance_fraction=var_fraction,
                equity_curve=eq,
                returns=ret,
                weight_history=wh,
                disabled_periods=disabled_periods,
            )

        # ── Correlation report ─────────────────────────────────────────────────
        correlation_report = _build_correlation_report(combined_strat_returns)

        # ── Allocator log DataFrame ────────────────────────────────────────────
        if all_alloc_changes:
            alloc_log_df = pd.DataFrame([
                {
                    "strategy_name": c.strategy_name,
                    "old_weight": c.old_weight,
                    "new_weight": c.new_weight,
                    "old_capital": c.old_capital,
                    "new_capital": c.new_capital,
                    "reason": c.reason,
                }
                for c in all_alloc_changes
            ])
        else:
            alloc_log_df = pd.DataFrame(columns=[
                "strategy_name", "old_weight", "new_weight",
                "old_capital", "new_capital", "reason",
            ])

        # ── Benchmark comparisons ──────────────────────────────────────────────
        benchmark: Optional[BenchmarkComparison] = None
        if self.run_benchmarks:
            benchmark = self._run_benchmarks(
                prices, specs, strategy_configs_for_alloc, port_m, attributions
            )

        result = MultiStrategyBacktestResult(
            windows=fold_results,
            combined_portfolio_equity=combined_portfolio_equity,
            combined_portfolio_returns=combined_portfolio_returns,
            initial_capital=self.initial_capital,
            final_equity=float(combined_portfolio_equity.iloc[-1]),
            total_return=port_m["total_return"],
            cagr=port_m["cagr"],
            sharpe=port_m["sharpe"],
            sortino=port_m["sortino"],
            max_drawdown=port_m["max_drawdown"],
            calmar=port_m["calmar"],
            allocator_turnover=allocator_turnover,
            attributions=attributions,
            correlation_report=correlation_report,
            allocator_log=alloc_log_df,
            benchmark=benchmark,
            metadata={
                "n_folds": len(fold_results),
                "strategies": [s.name for s in specs],
                "allocator_approach": self.allocator_approach,
                "allocate_interval": self.allocate_interval,
                "train_window": self.train_window,
                "test_window": self.test_window,
            },
        )
        self._result = result
        return result

    def get_result(self) -> Optional[MultiStrategyBacktestResult]:
        return self._result

    def save_csv_outputs(
        self,
        result: MultiStrategyBacktestResult,
        output_dir: str = "results",
    ) -> Dict[str, str]:
        """
        Write the four standard output files.

        Returns a dict of {label: filepath} for the files written.
        """
        import os
        os.makedirs(output_dir, exist_ok=True)
        paths: Dict[str, str] = {}

        # multistrat_equity.csv
        eq_df = pd.DataFrame({"portfolio": result.combined_portfolio_equity})
        for name, attr in result.attributions.items():
            eq_df[name] = attr.equity_curve
        path = os.path.join(output_dir, "multistrat_equity.csv")
        eq_df.to_csv(path)
        paths["equity"] = path

        # allocator_log.csv
        path = os.path.join(output_dir, "allocator_log.csv")
        result.allocator_log.to_csv(path, index=False)
        paths["allocator_log"] = path

        # correlation_history.csv
        path = os.path.join(output_dir, "correlation_history.csv")
        result.correlation_report.rolling_history.to_csv(path)
        paths["correlation_history"] = path

        # per_strategy_metrics.csv
        rows = []
        for name, attr in result.attributions.items():
            rows.append({
                "strategy_name": name,
                "symbols": ",".join(attr.symbols),
                "total_return": round(attr.total_return, 4),
                "cagr": round(attr.cagr, 4),
                "sharpe": round(attr.sharpe, 4),
                "sortino": round(attr.sortino, 4),
                "max_dd": round(attr.max_drawdown, 4),
                "calmar": round(attr.calmar, 4),
                "contribution_to_return": round(attr.contribution_to_portfolio_return, 4),
                "variance_fraction": round(attr.variance_fraction, 4),
            })
        path = os.path.join(output_dir, "per_strategy_metrics.csv")
        pd.DataFrame(rows).to_csv(path, index=False)
        paths["per_strategy_metrics"] = path

        logger.info("CSV outputs written to %s", output_dir)
        return paths

    # ── Window generation ──────────────────────────────────────────────────────

    def _generate_windows(self, n_clean: int) -> List[Tuple[int, int, int, int]]:
        windows = []
        cursor = 0
        while cursor + self.train_window + self.test_window <= n_clean:
            is_s = cursor
            is_e = cursor + self.train_window
            oos_s = is_e
            oos_e = min(oos_s + self.test_window, n_clean)
            windows.append((is_s, is_e, oos_s, oos_e))
            cursor += self.step_size
        return windows

    # ── Single-fold simulation ─────────────────────────────────────────────────

    def _run_multi_window(
        self,
        fold_id: int,
        prices: pd.DataFrame,
        ohlcv_per_spec: Dict[str, Dict[str, pd.DataFrame]],
        is_features: Dict[str, pd.DataFrame],
        oos_features: Dict[str, pd.DataFrame],
        start_equity: float,
        specs: List[StrategySpec],
        allocator: CapitalAllocator,
        portfolio_rm: PortfolioRiskManager,
    ) -> MultiStrategyWindowResult:
        """Execute one walk-forward OOS fold for all strategies simultaneously."""

        # ── 1. Train each strategy's HMM and build orchestrator ───────────────
        engines: Dict[str, HMMEngine] = {}
        orchs: Dict[str, StrategyOrchestrator] = {}
        n_hmm_states: Dict[str, int] = {}

        for spec in specs:
            hmm_cfg = {**_DEFAULT_HMM_CFG, **(spec.hmm_config or {})}
            _engine_kwargs = {
                "n_candidates", "n_init", "covariance_type", "min_train_bars",
                "stability_bars", "flicker_window", "flicker_threshold",
                "min_confidence", "min_covar",
            }
            engine = HMMEngine(**{k: v for k, v in hmm_cfg.items() if k in _engine_kwargs})
            engine.fit(is_features[spec.name].values)
            n_hmm_states[spec.name] = engine._n_states

            strat_cfg = _DEFAULT_STRAT_CFG.copy()
            sc = spec.strategy_config or {}
            strat_cfg["strategy"] = {
                **strat_cfg["strategy"],
                **sc.get("strategy", sc),
            }
            min_conf = hmm_cfg.get("min_confidence", 0.55)
            rebalance_thr = strat_cfg["strategy"].get("rebalance_threshold", 0.10)
            orch = StrategyOrchestrator(
                config=strat_cfg,
                regime_infos=engine.get_all_regime_info(),
                min_confidence=min_conf,
                rebalance_threshold=rebalance_thr,
            )

            # Warm up forward-pass on IS bars
            for row in is_features[spec.name].values:
                engine.update(row)

            engines[spec.name] = engine
            orchs[spec.name] = orch

            logger.info(
                "Fold %d strategy '%s': HMM n_states=%d",
                fold_id, spec.name, engine._n_states,
            )

        # ── 2. Build registry and proxy BaseStrategy instances ────────────────
        StrategyRegistry._reset()          # fresh singleton for this fold
        registry = StrategyRegistry.instance()
        for spec in specs:
            proxy = _BacktestProxy(spec.name)
            proxy.allocated_capital = start_equity / len(specs)
            registry.register(spec.name, proxy)

        # ── 3. Initialise per-strategy sub-portfolios ─────────────────────────
        # Equal split at fold start; allocator will rebalance after first interval
        initial_per_strat = (start_equity * (1.0 - self.reserve)) / len(specs)
        portfolio_reserve = start_equity * self.reserve

        strat_cash: Dict[str, float] = {s.name: initial_per_strat for s in specs}
        strat_shares: Dict[str, Dict[str, float]] = {
            s.name: {sym: 0.0 for sym in s.symbols} for s in specs
        }
        strat_prev_equity: Dict[str, float] = {s.name: initial_per_strat for s in specs}

        # ── 4. Tracking data structures ───────────────────────────────────────
        port_equity_curve: Dict[pd.Timestamp, float] = {}
        port_returns_dict: Dict[pd.Timestamp, float] = {}
        strat_equity_curves: Dict[str, Dict] = {s.name: {} for s in specs}
        strat_returns_dicts: Dict[str, Dict] = {s.name: {} for s in specs}
        weight_histories: Dict[str, Dict] = {s.name: {} for s in specs}
        all_alloc_changes: List[AllocationChange] = []
        all_trades: List[Dict] = []

        pending: Dict[str, Optional[Dict]] = {s.name: None for s in specs}
        bars_since_alloc = 0
        prev_total_equity = start_equity
        peak_total_equity = start_equity
        daily_start_equity = start_equity

        oos_timestamps = list(oos_features[specs[0].name].index)

        # ── 5. OOS bar-by-bar simulation ──────────────────────────────────────
        for t, bar_date in enumerate(oos_timestamps):
            if bar_date not in prices.index:
                continue

            # Current close prices per spec
            cur_px: Dict[str, Dict[str, float]] = {}
            for spec in specs:
                px: Dict[str, float] = {}
                for sym in spec.symbols:
                    if sym in prices.columns:
                        val = prices.loc[bar_date, sym]
                        if pd.notna(val) and val > 0:
                            px[sym] = float(val)
                cur_px[spec.name] = px

            # ── 5a. Execute pending signals (1-bar fill delay) ─────────────────
            for spec in specs:
                if pending[spec.name] is None:
                    continue
                pend = pending[spec.name]
                px = cur_px[spec.name]
                all_syms = list(set(spec.symbols) | set(strat_shares[spec.name].keys()))
                equity_pre = (
                    strat_cash[spec.name]
                    + sum(strat_shares[spec.name].get(s, 0.0) * px.get(s, 0.0) for s in all_syms)
                )
                for sym, target_wt in pend["weights"].items():
                    price = px.get(sym)
                    if not price:
                        continue
                    target_shr = equity_pre * target_wt / price
                    current_shr = strat_shares[spec.name].get(sym, 0.0)
                    delta = target_shr - current_shr
                    if abs(delta * price) < 1.0:
                        continue
                    sign = 1.0 if delta > 0 else -1.0
                    fill_px = price * (1.0 + sign * self.slippage_pct)
                    strat_cash[spec.name] -= delta * fill_px
                    strat_shares[spec.name][sym] = target_shr
                    all_trades.append({
                        "fold": fold_id,
                        "timestamp": bar_date,
                        "strategy": spec.name,
                        "symbol": sym,
                        "delta_shares": delta,
                        "fill_price": fill_px,
                        "trade_value": abs(delta * fill_px),
                        "slippage_cost": abs(delta * fill_px * self.slippage_pct),
                        "regime": pend.get("regime", ""),
                        "regime_prob": pend.get("regime_prob", 0.0),
                        "target_weight": target_wt,
                    })
                pending[spec.name] = None

                # Sync PRM with actual positions post-fill
                px_now = cur_px[spec.name]
                pos_usd = {
                    sym: strat_shares[spec.name].get(sym, 0.0) * px_now.get(sym, 0.0)
                    for sym in spec.symbols
                }
                portfolio_rm.update_strategy_positions(spec.name, pos_usd)

            # ── 5b. Mark to market ─────────────────────────────────────────────
            strat_equity_now: Dict[str, float] = {}
            for spec in specs:
                px = cur_px[spec.name]
                all_syms = list(set(spec.symbols) | set(strat_shares[spec.name].keys()))
                eq = (
                    strat_cash[spec.name]
                    + sum(strat_shares[spec.name].get(s, 0.0) * px.get(s, 0.0) for s in all_syms)
                )
                strat_equity_now[spec.name] = eq
                strat_equity_curves[spec.name][bar_date] = eq
                prev_eq = strat_prev_equity[spec.name]
                daily_ret = (eq / prev_eq - 1.0) if prev_eq > 0 else 0.0
                strat_returns_dicts[spec.name][bar_date] = daily_ret
                strat_prev_equity[spec.name] = eq

                proxy = registry.get(spec.name)
                if proxy:
                    proxy.record_daily_return(bar_date, daily_ret)

            total_equity = portfolio_reserve + sum(strat_equity_now.values())
            port_equity_curve[bar_date] = total_equity
            port_returns_dict[bar_date] = (
                (total_equity / prev_total_equity - 1.0) if prev_total_equity > 0 else 0.0
            )
            prev_total_equity = total_equity
            if total_equity > peak_total_equity:
                peak_total_equity = total_equity
            # Reset daily baseline at start of each new calendar day
            prev_date = bar_date - pd.tseries.offsets.BDay(1)
            if t == 0 or bar_date.date() != prev_date.date():
                daily_start_equity = total_equity

            # ── 5c. Health checks ──────────────────────────────────────────────
            registry.run_health_checks(bar_count=t)

            # ── 5d. Allocator rebalance (weekly) ──────────────────────────────
            bars_since_alloc += 1
            if bars_since_alloc >= self.allocate_interval:
                daily_dd_frac = max(0.0, -port_returns_dict[bar_date])
                changes = allocator.rebalance(
                    registry,
                    total_capital=total_equity,
                    daily_drawdown=daily_dd_frac,
                )
                all_alloc_changes.extend(changes)
                bars_since_alloc = 0

                # Transfer cash between sub-portfolios to hit new target capitals
                for spec in specs:
                    proxy = registry.get(spec.name)
                    if proxy is None:
                        continue
                    target_cap = proxy.allocated_capital
                    current_cap = strat_equity_now[spec.name]
                    delta_cash = target_cap - current_cap
                    # Cap at available reserve (positive delta) or strategy cash (negative delta)
                    if delta_cash > 0:
                        transfer = min(delta_cash, portfolio_reserve)
                        strat_cash[spec.name] += transfer
                        portfolio_reserve -= transfer
                    else:
                        # Clamp: never make strat cash more negative than -equity (margin floor)
                        safe_delta = max(delta_cash, -(strat_cash[spec.name]))
                        strat_cash[spec.name] += safe_delta
                        portfolio_reserve -= safe_delta  # reserve increases

            # Record weights
            for spec in specs:
                proxy = registry.get(spec.name)
                if proxy and proxy.is_enabled:
                    w = proxy.allocated_capital / max(total_equity, 1e-9)
                else:
                    w = 0.0
                weight_histories[spec.name][bar_date] = w

            # ── 5e. HMM update + signal generation ────────────────────────────
            for spec in specs:
                proxy = registry.get(spec.name)
                if proxy is None or not proxy.is_enabled:
                    continue

                oos_feat = oos_features[spec.name]
                if t >= len(oos_feat):
                    continue

                regime_state = engines[spec.name].update(oos_feat.values[t], bar_date)
                is_flickering = engines[spec.name].is_flickering()

                bars_for_signal: Dict[str, pd.DataFrame] = {}
                for sym in spec.symbols:
                    if sym not in ohlcv_per_spec[spec.name]:
                        continue
                    sym_ohlcv = ohlcv_per_spec[spec.name][sym]
                    try:
                        end_loc = sym_ohlcv.index.get_loc(bar_date) + 1
                    except KeyError:
                        continue
                    bars_for_signal[sym] = sym_ohlcv.iloc[max(0, end_loc - 250):end_loc]

                signals = orchs[spec.name].generate_signals(
                    spec.symbols, bars_for_signal, regime_state, is_flickering
                )

                # Skip NEUTRAL regime if configured
                skip_neutral = self.config.get("strategy", {}).get("skip_neutral_regime", False)
                if skip_neutral and regime_state.label == "NEUTRAL":
                    signals = []

                if not signals:
                    continue

                strat_eq = strat_equity_now[spec.name]
                scale = strat_eq / max(total_equity, 1e-9)
                approved_weights: Dict[str, float] = {}
                approved_stops: Dict[str, float] = {}

                for sig in signals:
                    # Scale signal to portfolio-relative pct for PRM
                    portfolio_pct = sig.position_size_pct * sig.leverage * scale
                    scaled_sig = copy.copy(sig)
                    scaled_sig.position_size_pct = portfolio_pct
                    scaled_sig.leverage = 1.0  # leverage already baked into portfolio_pct

                    strat_avail_cash = strat_cash[spec.name]
                    port_state = PortfolioState(
                        equity=total_equity,
                        cash=strat_avail_cash,
                        buying_power=strat_avail_cash,
                        positions=portfolio_rm.get_aggregate_positions(),
                        daily_pnl=total_equity - daily_start_equity,
                        peak_equity=peak_total_equity,
                        daily_start=daily_start_equity,
                        flicker_rate=int(is_flickering),
                    )
                    decision = portfolio_rm.validate_signal(scaled_sig, spec.name, port_state)

                    if decision.approved and decision.modified_signal is not None:
                        approved_portfolio_pct = decision.modified_signal.position_size_pct
                        # Unscale back to strategy-relative for execution
                        exec_wt = (approved_portfolio_pct / scale) if scale > 1e-9 else 0.0
                        exec_wt = min(exec_wt, 1.0)   # cap at 100% of sub-portfolio
                        approved_weights[sig.symbol] = exec_wt
                        approved_stops[sig.symbol] = sig.stop_loss

                if approved_weights:
                    pending[spec.name] = {
                        "weights": approved_weights,
                        "stop_losses": approved_stops,
                        "regime": regime_state.label,
                        "regime_prob": regime_state.probability,
                    }

        # ── 6. Build WindowResult ──────────────────────────────────────────────
        first_is = is_features[specs[0].name]
        first_oos = oos_features[specs[0].name]
        return MultiStrategyWindowResult(
            fold_id=fold_id,
            train_start=first_is.index[0],
            train_end=first_is.index[-1],
            test_start=first_oos.index[0],
            test_end=first_oos.index[-1],
            portfolio_equity=pd.Series(port_equity_curve, name="portfolio"),
            portfolio_returns=pd.Series(port_returns_dict, name="portfolio_returns"),
            strategy_equity={
                n: pd.Series(v, name=n) for n, v in strat_equity_curves.items()
            },
            strategy_returns={
                n: pd.Series(v, name=n) for n, v in strat_returns_dicts.items()
            },
            weight_history={
                n: pd.Series(v, name=n) for n, v in weight_histories.items()
            },
            allocator_changes=all_alloc_changes,
            trades=all_trades,
            n_hmm_states=n_hmm_states,
        )

    # ── Benchmark comparisons ──────────────────────────────────────────────────

    def _run_benchmarks(
        self,
        prices: pd.DataFrame,
        specs: List[StrategySpec],
        strategy_configs: Dict,
        port_metrics: Dict,
        attributions: Dict[str, StrategyAttribution],
    ) -> BenchmarkComparison:
        """Compute benchmark comparisons; may run another full backtester pass."""

        # Equal-weight: reuse attribution metrics but with equal weighting
        # Approximate by treating each strategy's return equally weighted
        eq_returns_list = [attributions[s.name].returns for s in specs]
        if eq_returns_list:
            eq_combined = pd.concat(eq_returns_list, axis=1).mean(axis=1)
            eq_eq = (1.0 + eq_combined).cumprod() * self.initial_capital
            eq_m = _metrics(
                eq_combined,
                self.initial_capital,
                float(eq_eq.iloc[-1]) if len(eq_eq) > 0 else self.initial_capital,
            )
        else:
            eq_m = {"sharpe": 0.0, "calmar": 0.0}

        # Best / worst single by Calmar
        best_name = max(attributions, key=lambda n: attributions[n].calmar)
        worst_name = min(attributions, key=lambda n: attributions[n].calmar)

        # Buy-and-hold: most-traded symbol (appear in most specs)
        from collections import Counter
        all_syms = [sym for spec in specs for sym in spec.symbols]
        most_common_sym = Counter(all_syms).most_common(1)[0][0]
        if most_common_sym in prices.columns:
            p = prices[most_common_sym].dropna()
            bah_return = float(p.iloc[-1] / p.iloc[0] - 1.0) if len(p) > 1 else 0.0
        else:
            bah_return = 0.0

        portfolio_calmar = port_metrics["calmar"]
        best_calmar = attributions[best_name].calmar

        return BenchmarkComparison(
            portfolio_calmar=portfolio_calmar,
            portfolio_sharpe=port_metrics["sharpe"],
            equal_weight_calmar=eq_m["calmar"],
            equal_weight_sharpe=eq_m["sharpe"],
            best_single_name=best_name,
            best_single_calmar=best_calmar,
            best_single_sharpe=attributions[best_name].sharpe,
            worst_single_name=worst_name,
            worst_single_calmar=attributions[worst_name].calmar,
            buy_and_hold_symbol=most_common_sym,
            buy_and_hold_total_return=bah_return,
            portfolio_beats_best_calmar=portfolio_calmar > best_calmar,
        )
